# Auto-merge dev into master if all tests pass and this pipeline runs on dev branch
- script: |
    git config --global user.email "pipeline@azure.com"
    git config --global user.name "Azure Pipeline"
    git checkout master
    git pull origin master
    git merge dev --no-ff -m "Auto-merge dev into master after successful pipeline"
    git push origin master
  displayName: 'Merge dev into master if all tests pass'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  JWT_SECRET: $(jwt)
  JWT_EXPIRES_IN: '14d'
  JWT_COOKIE_EXPIRES_IN: 14
  DATABASE: $(db)
  DATABASE_PASSWORD: $(dbpass)
  TEST_USER_PASSWORD: $(pwd)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install --include=dev
  displayName: 'Install dependencies including devDependencies'

# - script: |
#     npm run server-prod
#   displayName: 'Start Server'
#   env:
#     DATABASE: $(DATABASE)
#     DATABASE_PASSWORD: $(DATABASE_PASSWORD)

- script: |
    npm run test-be
  displayName: 'Run backend unit tests'
  env:
    JWT_SECRET: $(JWT_SECRET)
    TEST_USER_PASSWORD: $(TEST_USER_PASSWORD)
    DATABASE: $(DATABASE)
    DATABASE_PASSWORD: $(DATABASE_PASSWORD)

- script: |
    npm run test-fe
  displayName: 'Run frontend unit tests'
  env:
    NODE_ENV: development

# - script: |
#     npm run inte-test
#   displayName: 'Run integration tests'

- script: |
    npm run build
  displayName: 'Build frontend (Vite)'
  env:
    NODE_ENV: production
