# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  NODE_ENV: 'production'
  JWT_SECRET: $(jwt)
  JWT_EXPIRES_IN: '14d'
  JWT_COOKIE_EXPIRES_IN: 14
  DATABASE: $(db)
  DATABASE_PASSWORD: $(dbpass)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    # npm run test
  displayName: 'Run tests'

- script: |
    npm run build
  displayName: 'Build frontend (Vite)'
