# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  JWT_SECRET: $(jwt)
  JWT_EXPIRES_IN: "14d"
  JWT_COOKIE_EXPIRES_IN: 14
  DATABASE: $(db)
  DATABASE_PASSWORD: $(dbpass)
  TEST_USER_PASSWORD: $(pwd)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install --include=dev
    displayName: "Install dependencies including devDependencies"

  - script: |
      npm run test-fe
    displayName: "Run frontend unit tests"
    env:
      NODE_ENV: development

  - script: |
      npm run test-be
    displayName: "Run backend unit tests"
    env:
      JWT_SECRET: $(JWT_SECRET)
      TEST_USER_PASSWORD: $(TEST_USER_PASSWORD)

  # - script: |
  #     npm run inte-test
  #   displayName: 'Run integration tests'

  - script: |
      npm run build
    displayName: "Build frontend (Vite)"
    env:
      NODE_ENV: production
